spring:
    application:
        name: resource-oriented-architecture
    datasource:
        url: jdbc:h2:mem:/db 
        username: admin 
        password: 
    jpa:
        hibernate:
            ddl-auto: update